blueprint:
  name: Day Modes
  description:
    This blueprint is built to set a helper (input_select.modes) to the following five states
    (Away, Morning, Day, Evening, Night).
    This helper is used by this blueprint to set Away if no family members or guests are at home.
    The other ones are set for different times of the day if anyone is home.
  domain: automation
  source_url: https://gist.github.com/ticstyle/bdc6f07a00d4f3d97e4967018f58c9e6

  # Inputs
  input:
    input_select_target:
      name: Input Select Helper
      description: The input select helper with (Away, Morning, Day, Evening, Night) options. Automaticly selected if named "input_select.modes".
      default: input_select.modes
      selector:
        entity:
          domain: input_select
    home_zone_target:
      name: Home Zone
      description: The zone you call home.
      default: zone.home
      selector:
        entity:
          domain: zone
    morning_time:
      name: Morning Time
      description: Time to set morning mode.
      default: "06:00:00"
      selector:
        time:
    day_time:
      name: Day Time
      description: Time to set day mode.
      default: "09:00:00"
      selector:
        time:
    evening_time:
      name: Evening Time
      description: Time to set evening mode.
      default: "20:00:00"
      selector:
        time:
    night_time:
      name: Night Time
      description: Time to set night mode.
      default: "23:00:00"
      selector:
        time:

# Triggers
trigger:
  - platform: time
    at: !input morning_time
    id: morning
  - platform: time
    at: !input day_time
    id: day
  - platform: time
    at: !input evening_time
    id: evening
  - platform: time
    at: !input night_time
    id: night
  - platform: numeric_state
    entity_id: !input home_zone_target
    below: 1
    id: no_one_home
  - platform: numeric_state
    entity_id: !input home_zone_target
    id: anyone_home
    above: 0

# Automation Mode
mode: restart
max_exceeded: silent

# Conditions
condition: []

# Actions
action:
  choose:
    # Morning
    - conditions:
        - condition: and
          conditions:
            - condition: or
              conditions:
                - condition: trigger
                  id: morning
                - condition: trigger
                  id: anyone_home
            - condition: numeric_state
              entity_id: !input home_zone_target
              above: 0
            - condition: not
              conditions:
                - condition: state
                  entity_id: !input home_zone_target
                  state: Morning
            - condition: time
              after: !input morning_time
              before: !input day_time
      sequence:
        - service: input_select.select_option
          data:
            option: "Morning"
          target:
            entity_id: !input input_select_target

    # Day
    - conditions:
        - condition: and
          conditions:
            - condition: or
              conditions:
                - condition: trigger
                  id: day
                - condition: trigger
                  id: anyone_home
            - condition: numeric_state
              entity_id: !input home_zone_target
              above: 0
            - condition: not
              conditions:
                - condition: state
                  entity_id: !input home_zone_target
                  state: Day
            - condition: time
              after: !input day_time
              before: !input evening_time
      sequence:
        - service: input_select.select_option
          data:
            option: "Day"
          target:
            entity_id: !input input_select_target

    # Evening
    - conditions:
        - condition: and
          conditions:
            - condition: or
              conditions:
                - condition: trigger
                  id: evening
                - condition: trigger
                  id: anyone_home
            - condition: numeric_state
              entity_id: !input home_zone_target
              above: 0
            - condition: not
              conditions:
                - condition: state
                  entity_id: !input home_zone_target
                  state: Evening
            - condition: time
              after: !input evening_time
              before: !input night_time
      sequence:
        - service: input_select.select_option
          data:
            option: "Evening"
          target:
            entity_id: !input input_select_target

    # Night
    - conditions:
        - condition: and
          conditions:
            - condition: or
              conditions:
                - condition: trigger
                  id: night
                - condition: trigger
                  id: anyone_home
            - condition: numeric_state
              entity_id: !input home_zone_target
              above: 0
            - condition: not
              conditions:
                - condition: state
                  entity_id: !input home_zone_target
                  state: Night
            - condition: time
              after: !input night_time
              before: !input morning_time
      sequence:
        - service: input_select.select_option
          data:
            option: "Night"
          target:
            entity_id: !input input_select_target

    # Away
    - conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: no_one_home
            - condition: numeric_state
              entity_id: !input home_zone_target
              below: 1
      sequence:
        - service: input_select.select_option
          data:
            option: "Away"
          target:
            entity_id: !input input_select_target
